services:
  # The following services are built from Dockerfiles located in the respective directories
  auth-service:
    build:
      context: ./auth_service
      dockerfile: ../auth_service/Dockerfile
    restart: unless-stopped
    init: true
    env_file: ./auth_service/.env
    ports:
      - "3000:3000"
    networks:
      - backend

  products-service:
    build:
      context: ./products_services
      dockerfile: ../products_services/Dockerfile
    restart: unless-stopped
    init: true
    env_file: ./products_services/.env
    ports:
      - "3001:3001"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3000  # 👈 Key line added
    networks:
      - backend

  client:
    build:
      context: ./client
      dockerfile: ../client/Dockerfile
    restart: unless-stopped
    init: true
    # Exposes the Vite preview server on port 4173
    ports:
      - "4173:4173"
    networks:
      - backend
    depends_on:
      - auth-service
      - products-service


# Shared network for inter-service communication
networks:
  backend:
    driver: bridge

