apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: ds-microservices_assignment-notification-service:latest # Your locally built image
        imagePullPolicy: Never 
        ports:
        - containerPort: 3002
        env:
        - name: PORT  # Add other environment variables if needed
          value: "3002"
        - name: TWILIO_ACCOUNT_SID
          value: "ACe04682c8715dab576e17cd468e326898" 
        - name: TWILIO_AUTH_TOKEN
          value: "32a54ddd8a73e20ec0436fad4ba02077"   
        - name: TWILIO_PHONE_NUMBER
          value: "+17343611980"
        - name : EMAIL_USER
          value: "dushmantha7273@gmail.com"
        - name : EMAIL_PASS
          value: "szbq hxng wlli tpnc"
        resources:
          requests:
            memory: "256Mi"   # Minimum amount of memory the container needs
            cpu: "250m"       # Minimum amount of CPU the container needs
          limits:
            memory: "512Mi"   # Maximum memory the container can use
            cpu: "500m"       # Maximum CPU the container can use

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 3002         # The port on which the service will be exposed inside the cluster
      targetPort: 3002   # The port on the container itself
      nodePort: 30002    # The external port accessible via Kubernetes node IP
  type: NodePort
