apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ds-microservices_assignment-products-service:latest
          imagePullPolicy: Never # Use the locally built image
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              value: "mongodb+srv://it22056252:cnPlCee4jr5SszIx@seproject.olebn.mongodb.net/?retryWrites=true&w=majority&appName=seproject"
            - name: PORT
              value: "3001"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:3000" 
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
