apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
      - name: restaurant-service
        image: ds-microservices_assignment-restaurant-service:latest # Your locally built image
        imagePullPolicy: Never 
        ports:
        - containerPort: 3005
        env:
        - name: MONGO_URI  # Replace with your actual environment variables
          value: "mongodb+srv://it22056252:cnPlCee4jr5SszIx@seproject.olebn.mongodb.net/?retryWrites=true&w=majority&appName=seproject"
        - name: PORT  # Add other environment variables if needed
          value: "3005"
        - name: CLOUDINARY_API_SECRET
          value: "wtIRq-axFaDZHmyBpUYjG4UCifo"
        - name: CLOUDINARY_API_KEY
          value: "424691573848857"
        - name: CLOUDINARY_CLOUD_NAME
          value: dpdrfruja

        resources:
          requests:
            memory: "256Mi"   # Minimum amount of memory the container needs
            cpu: "250m"       # Minimum amount of CPU the container needs
          limits:
            memory: "512Mi"   # Maximum memory the container can use
            cpu: "500m"       # Maximum CPU the container can use

---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant-service
  ports:
    - protocol: TCP
      port: 3005        # The port on which the service will be exposed inside the cluster
      targetPort: 3005   # The port on the container itself
      nodePort: 30005    # The external port accessible via Kubernetes node IP
  type: NodePort
